//
// Created by Bram on 14/06/2023.
//

#ifndef INC_3DGAMEBRIDGE_WEAVER_FLAGS_H
#define INC_3DGAMEBRIDGE_WEAVER_FLAGS_H

#endif //INC_3DGAMEBRIDGE_WEAVER_FLAGS_H
#pragma once

enum class WeaverFlags {
    SRGB_ENABLE_DEBUG_OVERLAY_OR_WHATEVER,
    SRGB_MANUAL_SET_CAMERA_LATENCY_VALUE,
    SRGB_MANUAL_SET_CAMERA_LATENCY_IN_FRAMES__VALUE
};
